### ISSUE TITLE
User Registration

### ISSUE THREAD

**Issue by sahlaouiahmed** [sahlaouiahmed/CI_FinalProject#1]
* As a visitor, I can register for an account so that I can log in and access personalized features.
  - Acceptance criteria:
    - Users can sign up using an email and password.
    - Email verification is required for account activation.
    - Users receive a confirmation email with a verification link.

**Comment by jjyutm4532** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modify the Django settings to enable email verification for new user registrations.

You can review changes in this commit: https://github.com/jjyutm4532/sahlaouiahmed-CI_FinalProject-1/commit/b25ba4fda1f45e879d3c435f80570f68ed92f4cc.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
